name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    working-directory: server
    steps:
      - uses: actions/checkout@v1
      - name: Run Tests
        run:
          working-directory: server
          npm install
