name: Unit Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]

jobs:
  Jest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install packages
        working-directory: server/
        run: |
          npm install
          npm test
      -name: 
